name: Build for Pull Request

on:
  pull_request:
    

jobs:
  build_server_client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name: install npm 7
        run: npm install -g npm@7

      - name: install server
        run: npm install --force
        working-directory: server

      - name: build server
        run: npm run build
        working-directory: server
        env:
          NODE_ENV: 'production'

      - name: install client
        run: npm install
        working-directory: client

      - name: build client
        run: npm run build
        working-directory: client
        env:
          REACT_APP_BACKEND: https://kabootar-mail.herokuapp.com
