name: Build for Pull Request

on:
  pull_request:
    

jobs:
  build_server_client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name: install npm 7
        run: npm install -g npm@7

      - name: lerna install
        run: npm install

      - name: build server
        run: npm run build
        working-directory: server
        env:
          ATLAS_URI: mongodb+srv://lordneon:mongodb123@cluster0.ciluy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

      - name: build client
        run: npm run build
        working-directory: client
        env:
          REACT_APP_BACKEND: https://kabootar-mail.herokuapp.com
